global:
    ros__parameters:
        topic_prefix: "/fb"

beacon:
    ros__parameters:
        name: "beacon"

blocky:
    ros__parameters:
        name: "blocky"

capabilities:
    ros__parameters:
        name: "capabilities"
        function: "harvester"
        color: "#ff0000"
        uuid: "00000000-0000-0000-0000-000000000000"
